### PR TITLE
Pr

### PR DESCRIPTION
**Pull request by paragonie-scott**

### CODE REVIEW

**Comment by paragonie-scott** [comment]
Sometimes I hate github.

**Comment by glensc** [comment]
hate what here?

**Comment by paragonie-scott** [comment]
"OK, I'll try `git push --force`"  
"Everything up to date. (Huehue that did nothing.)"  
"Fine, I'll push to a new branch then pull request it."  
"OK, we'll cooperate now."

**Comment by glensc** [comment]
if i mess up, i rather do `git reset --hard origin/master` and redo merge rather `--force` in push

**Pull request merged**
